server:
  port: 8089
  tomcat:
    max-http-form-post-size: 1000MB

spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://onetab.ck39dp9w2h39.ap-northeast-2.rds.amazonaws.com:3306/practice
    #    url: jdbc:mariadb://localhost:3306/innodb
    username: admin
    password: chunjae12#$

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  devtools:
    livereload:
      enabled: true


#logging.level:
#  org.hibernate.SQL: debug
# org.hibernate.type: trace

mybatis:
  mapper-locations: mappers/*.xml
  #type-aliases-package: com.example.onetab.mapper
  #configuration:
  #  cache-enabled: true
  #  default-statement-timeout: 300
  #  map-underscore-to-camel-case: true
  #  use-generated-keys: true
  config-location: classpath:mapper/config/sql-mapper-config.xml

